# -*- mode: ruby -*-
# vi: set ft=ruby :
# use from vagrant host (replace default Vagrantfile)

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
    end
	config.vm.define "controller" do |controller|
		controller.vm.box = "bento/ubuntu-16.04"
		controller.vm.hostname = "controller"
		controller.vm.network :private_network, ip: "10.10.10.10"
		controller.vm.provision :shell, path: 'vagrant-controller-setup.sh'
    end
	(1..3).each do |i|
		config.vm.define "node#{i}" do |node|
			node.vm.box = "bento/ubuntu-16.04"
			node.vm.hostname = "node#{i}"
			node.vm.network :private_network, ip: "10.10.10.1#{i}"
		end
	end
	(1..3).each do |j|
		config.vm.define "dev#{j}" do |dev|
			dev.vm.box = "bento/ubuntu-16.04"
			dev.vm.hostname = "dev#{j}"
			dev.vm.network :private_network, ip: "10.10.10.2#{j}"
		end
	end
end