# -*- mode: ruby -*-
# vi: set ft=ruby :
#controller.vm.provision :shell, path: 'ubuntu-setup.sh'

Vagrant.configure("2") do |config|
	config.vm.define "controller" do |controller|
		controller.vm.box = "bento/ubuntu-16.04"
		controller.vm.hostname = "controller"
		controller.vm.network :private_network, ip: "10.10.10.10"
		controller.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
        end
    end
end

(1..4).each do |i|
	config.vm.define "node#{i}" do |node|
		node.vm.box = "bento/ubuntu-16.04"
		node.vm.hostname = "node#{i}"
		node.vm.network :private_network, ip: "10.10.10.1#{i}"
		node.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
        end
    end
end

(1..3).each do |j|
	config.vm.define "dev#{j}" do |dev|
		dev.vm.box = "bento/ubuntu-16.04"
		dev.vm.hostname = "dev#{j}"
		dev.vm.network :private_network, ip: "10.10.10.2#{j}"
		dev.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
        end
    end
end