- name: "Install inventory mapping and setup all remote nodes"
  hosts: devs, nodes
  #- gather_facts: false # comment out if preferred
  become: true # newer ansible version of 'sudo'
  pre_tasks:
  - name: "Add Ansible inventory mappings to /etc/hosts"
    blockinfile:
      path: '/etc/hosts'
      block: |
        {% for host in groups['all'] %}
        {{ hostvars[host].ansible_host }} {{ host }}
        {% endfor %}
       
- name: "Update all nodes"
  hosts: all
  become: true # newer ansible version of 'sudo'
  tasks:
  - name: "Install updates for RedHat OS Families"
    yum: name=* state=latest update_cache=yes
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
  - name: "Install updates for Debian OS Families"
    apt: upgrade=dist update_cache=yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Kali' or ansible_distribution == 'Ubuntu'

- name: "Install and setup dev environments"
  hosts: devs
  become: true # newer ansible version of 'sudo'
  vars:
    group: 'devs'
  tasks:
    - name: "Install dev packages"
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=latest update_cache=yes
      with_items: 
        - git
        - neovim
    - name: "Setup dev folder"
      file:
        path: '/{{ group }}'
        state: directory
    - name: "Add dev group"
      group:
        name: '{{ group }}'
        state: present

- name: "Install and setup node environments"
  hosts: nodes
  vars:
    home: '/home/vagrant' # can change depending on hierarchy pref
    images: '/home/vagrant/images' # can change depending on hierarchy pref
  tasks:
    - name: "find the files in home directory"
      shell: 'ls -lah {{ home }}'
    - name: "create a file in home directory"
      file:
        path: '{{ home }}/awesome.txt'
        state: touch
    - name: "create the picture folder"
      file:
        path: '{{ images }}'
        state: directory