# store in controller host
# this is just an example
- hosts: devs
  become: yes
  tasks:
    - name: "install git"
      apt:
        name: git
        state: latest
    - name: "install neovim"
      apt:
        name: neovim
        state: latest
    - name: "setup dev folder"
      file:
        path: /code
        state: directory
    - name: "add dev group"
      group:
        name: developers
        state: present
