--- # this is just an example
- hosts: nodes
  vars:
    home: "/home/vagrant"
    images: "/home/vagrant/images"
  tasks:
    - name: "find the files in home directory"
      shell: "ls -lah {{ home }}"
    - name: "create a file in home directory"
      file:
        path: "{{ home }}/awesome.txt"
        state: touch
    - name: "create the picture folder"
      file:
        path: "{{ images }}"
        state: directory